### PR TITLE
Update command and require in documentation

### PR DESCRIPTION
**Pull request by enzolutions**

### CODE REVIEW

**Comment by yosymfony** [comment]
`new:site` is for Spress 1.1.0 and until 2.0.0 `site:new` is a alias.

**Comment by enzolutions** [comment]
Well I have 1.1.0 and doesn't work.

**Comment by yosymfony** [comment]
Work fine for me. Do you really have 1.1.0 RC?

**Comment by enzolutions** [comment]
$ spress -v
Spress - The static site generator version 1.1.0

**Pull request merged**
